[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.codespell]
check-filenames = true
check-hidden = true
skip = "*.csv,*.html,*.json,*.jsonl,*.pdf,*.txt,*.ipynb"

[tool.llamahub]
contains_example = false
import_path = "llama_index.readers.gemini"

[tool.poetry]
authors = ["Sumit Aryal <sumitaryal310@hotmail.com>"]
description = "Gemini PDF Reader for LlamaIndex"
keywords = ["gemini", "pdf", "reader"]
license = "MIT"
name = "llama-index-readers-gemini"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
pdf2image = "^1.17.0"
google-genai = "^1.5.0"
llama-index-core = "^0.12.22"
